### ISSUE TITLE
Improved welcome message

### ISSUE THREAD

**Issue by arnavsharma93** [ffledgling/dtella#11]
A welcome message showing the list of available commands and rules of land.

**Comment by nehaljwani** [comment]
There is a patch under review for MOTD. Users can always type !help for viewing available commands. This can probably be mentioned at the end of the MOTD.

**Comment by ffledgling** [comment]
This problem is now being taken care of using the `!TOPIC`, so closing this issue and marking as resolved. If there are issues down the road, we can re-visit our decision and/or re-open the issue.
